name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        brew shellenv | sed 's/^export //g' >> $GITHUB_ENV
    
    - name: Install dependencies
      run: |
        brew install parallel jq

    - name: Suppress GNU Parallel Citation Notice
      run: parallel --citation

    - name: Make script executable
      run: chmod +x ./application_size_checker.sh

    - name: Run script
      run: ./application_size_checker.sh

