name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $GITHUB_ENV
        eval "$(/opt/homebrew/bin/brew shellenv)"
        
    - name: Set up Homebrew environment
      run: |
        echo "Adding Homebrew to PATH"
        echo 'HOMEBREW_PREFIX="/opt/homebrew"' >> $GITHUB_ENV
        echo 'PATH="/opt/homebrew/bin:$PATH"' >> $GITHUB_ENV
        echo 'HOMEBREW_CELLAR="/opt/homebrew/Cellar"' >> $GITHUB_ENV
        echo 'HOMEBREW_REPOSITORY="/opt/homebrew"' >> $GITHUB_ENV
        echo 'MANPATH="/opt/homebrew/share/man:$MANPATH"' >> $GITHUB_ENV
        echo 'INFOPATH="/opt/homebrew/share/info:$INFOPATH"' >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        brew install parallel jq

    - name: Suppress GNU Parallel Citation Notice
      run: parallel --citation

    - name: Make script executable
      run: chmod +x ./application_size_checker.sh

    - name: Run script
      run: ./application_size_checker.sh

