name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        eval "$(/opt/homebrew/bin/brew shellenv)"

    - name: Install dependencies
      env:
        PATH: /opt/homebrew/bin:$PATH
      run: |
        brew install parallel jq

    - name: Suppress GNU Parallel Citation Notice
      env:
        PATH: /opt/homebrew/bin:$PATH
      run: parallel --citation

    - name: Make script executable
      run: chmod +x ./application_size_checker.sh

    - name: Run script
      env:
        PATH: /opt/homebrew/bin:$PATH
      run: ./application_size_checker.sh

